language: python

install:
  - pip install -r requirements.txt
  
 jobs:
  include:
    - stage: "Documentation"
      install:
        - pip install sphinx
        - pip install sphinx_rtd_theme
        - pip install -e .
      script:
        - (cd docs && make html)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in travis-ci.com dashboard
        keep-history: true
        on:
          branch: master
        local_dir: ./docs/build/html/
   
